# Generated by Django 3.1.7 on 2021-03-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='答え')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='質問')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memo.category', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, to='memo.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memo.category', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, to='memo.Tag', verbose_name='タグ')),
            ],
        ),
    ]
